### ISSUE TITLE
프론트 이슈 해결 요청

### ISSUE THREAD

**Issue by runnz121** [ToyCommunity/backend#32]
## 작업 설명
어떤 작업인지 간단하게 설명하기

## todo
- [x] CORS 에러 설정
- [x] 가세글 생성시 카테고리 디폴트값 설정
- [x] 데이터 기존 데이터로 유지
- [x] json 응답 카멜케이스로 변경 
- [x] 게시글 페이지 리스트 1 부터 시작
