### ISSUE TITLE
빌드 스크립트 수정

### ISSUE THREAD

**Issue by runnz121** [ToyCommunity/backend#35]
## 작업 설명
어떤 작업인지 간단하게 설명하기
배포 후 어플리케이션 실행이 안됨, 스크립트 수정을 통해서 이를 해결

## todo
- [x] code deploy 시 배포 단계에서 application start, stop 스크립트를 분리
- [x] start script 작성
- [x] stop script 작성
